const CONSTANTS = Object.freeze({
  MIN_LOTTO_NUMBER: 1,
  MAX_LOTTO_NUMBER: 45,
  LOTTO_LENGTH: 6,
  LOTTO_PRICE: 1000,
  MIN_PURCHASE_AMOUNT: 1000,
  MAX_PURCHASE_AMOUNT: 100000,
  DEFAULT_VALUE: 0,
});

export default CONSTANTS;
