const CONSTANTS = Object.freeze({
  DEFAULT_VALUE: 0,
  MIN_LOTTO_NUMBER: 1,
  MAX_LOTTO_NUMBER: 45,
  LENGTH: 6,
  PRICE_UNIT: 1000,
  MIN_PURCHASE_AMOUNT: 1000,
  MAX_PURCHASE_AMOUNT: 100000,
});

export default CONSTANTS;
