const MAX_NUMBER = 45;
const MIN_NUMBER = 1;

const LOTTO_LENGTH = 6;

const MULTIPLE = 1000;

export const CONTANT = { MAX_NUMBER, MIN_NUMBER, LOTTO_LENGTH, MULTIPLE };
export { MAX_NUMBER, MIN_NUMBER, LOTTO_LENGTH, MULTIPLE };
