const SIX_NUMBERS_ERROR_MESSAGE = '로또 번호는 6개여야 합니다.';
const DUPLICATE_ERROR_MESSAGE = '로또 번호는 중복되지 않아야 합니다';
const INTEGER_ERROR_MESSAGE = '로또 번호는 정수여야 합니다.';
const INRANGE_ERROR_MESSAGE = '로또 번호는 1이상 45이하여야 합니다.';
const ASCENDING_ORDER_ERROR_MESSAGE = '로또 번호는 오름차순이여야 합니다.';

export {
  SIX_NUMBERS_ERROR_MESSAGE,
  DUPLICATE_ERROR_MESSAGE,
  INTEGER_ERROR_MESSAGE,
  INRANGE_ERROR_MESSAGE,
  ASCENDING_ORDER_ERROR_MESSAGE,
};
