const MESSAGE_PURCHASING_AMOUNT = "구입금액을 입력해 주세요.";
const MESSAGE_PURCHASING_NUMBER = "개를 구매했습니다.";

const MESSAGE_WINNING_NUMBER = "당첨 번호를 입력해 주세요.";

const MESSAGE_BONUS_NUMBER = "보너스 번호를 입력해 주세요.";

const MESSAGE_WINNING_INFO = "당첨 통계";
const MESSAGE_WINNING_BLANK = "---";
const MESSAGE_WINNING_THREE = "3개 일치 (5,000원) - ";
const MESSAGE_WINNING_FOUR = "4개 일치 (50,000원) - ";
const MESSAGE_WINNING_FIVE = "5개 일치 (1,500,000원) - ";
const MESSAGE_WINNING_BONUS = "5개 일치, 보너스 볼 일치 (30,000,000원) - ";
const MESSAGE_WINNING_ALL = "6개 일치 (2,000,000,000원) - ";
const MESSAGE_RATE = "총 수익률은 ";

const MESSAGE_COUNT_UNIT = "개";
const MESSAGE_RATE_UNIT = "%입니다.";

export {
  MESSAGE_PURCHASING_AMOUNT,
  MESSAGE_PURCHASING_NUMBER,
  MESSAGE_WINNING_NUMBER,
  MESSAGE_BONUS_NUMBER,
  MESSAGE_WINNING_INFO,
  MESSAGE_WINNING_BLANK,
  MESSAGE_WINNING_THREE,
  MESSAGE_WINNING_FOUR,
  MESSAGE_WINNING_FIVE,
  MESSAGE_WINNING_BONUS,
  MESSAGE_WINNING_ALL,
  MESSAGE_RATE,
  MESSAGE_COUNT_UNIT,
  MESSAGE_RATE_UNIT,
};
