const NUMBERS = Object.freeze({
  start_number: 1,
  piece: 6,
  end_number: 45,
  zero: 0,
  rank_stack: new Array(5).fill(0),
  purchase_money: 1000,
  percent: 100,
  stack_add: 1,
  three_match: 3,
  four_match: 4,
  five_match: 5,
  six_match: 6,
  first_place: 0,
  second_place: 1,
  third_place: 2,
  four_place: 3,
  five_place: 4,
  rank_index: 1,
  profit_rounded: 1,
  array_all_index: 4,
  default_value : 0,
});

export default NUMBERS;
