const NUMBERS = Object.freeze({
  LOTTO_PRICE: 1000,
  MISS_STATE: 0,
  BONUS_STATE: 1,
  HIT_STATE: 2,
  NUMBER_OF_LOTTO_NUMBERS: 6,
  LOTTO_NUMBER_LOWER: 1,
  LOTTO_NUMBER_UPPER: 45,
});

export default NUMBERS;
