const LOTTO_NUMBER_COUNT = 6;
const MAX_LOTTO_NUMBER = 45;
const MIN_LOTTO_NUMBER = 1;

const MIN_AMOUNT = 1000;

const MAX_BONUS_COUNT = 1;

export { LOTTO_NUMBER_COUNT, MAX_LOTTO_NUMBER, MIN_LOTTO_NUMBER, MIN_AMOUNT, MAX_BONUS_COUNT };
