const LOTTO_NUMBER_COUNT = 6;
const MAX_LOTTO_NUMBER = 45;
const MIN_LOTTO_NUMBER = 1;

const WINNING_THREE = 3;
const WINNING_THREE_BONUS = 3.5;
const WINNING_FOUR = 4;
const WINNING_FOUR_BOUNS = 4.5;
const WINNING_FIVE = 5;
const WINNING_FIVE_BONUS = 5.5;
const WINNING_SIX = 6;
const WINNING_SIX_BONUS = 6.5;

const PRIZE_WINNING_THREE = 5000;
const PRIZE_WINNING_FOUR = 50000;
const PRIZE_WINNING_FIVE = 1500000;
const PRIZE_WINNING_FIVE_BONUS = 30000000;
const PRIZE_WINNING_SIX = 2000000000;

const WINNING_SCORE = 1;
const BONUS_SCORE = 0.5;

const MIN_AMOUNT = 1000;

const MAX_BONUS_COUNT = 1;

const WINNING_DIVISION = ",";

const PERCENTAGE = 100;

export {
  LOTTO_NUMBER_COUNT,
  MAX_LOTTO_NUMBER,
  MIN_LOTTO_NUMBER,
  MIN_AMOUNT,
  MAX_BONUS_COUNT,
  WINNING_DIVISION,
  PERCENTAGE,
  WINNING_THREE,
  WINNING_THREE_BONUS,
  WINNING_FOUR,
  WINNING_FOUR_BOUNS,
  WINNING_FIVE,
  WINNING_FIVE_BONUS,
  WINNING_SIX,
  WINNING_SIX_BONUS,
  WINNING_SCORE,
  BONUS_SCORE,
  PRIZE_WINNING_THREE,
  PRIZE_WINNING_FOUR,
  PRIZE_WINNING_FIVE,
  PRIZE_WINNING_FIVE_BONUS,
  PRIZE_WINNING_SIX,
};
