const ERROR_MESSAGE_HEADER = "[ERROR]";

const ERROR_MESSAGE = {
  NOT_VALID_PURCHASE_AMOUNT: `${ERROR_MESSAGE_HEADER} 구입금액은 0보다 큰 숫자여야 합니다.`,
  NOT_VALID_PURCHASE_AMOUNT_UNIT: `${ERROR_MESSAGE_HEADER} 구입금액은 1000의 배수여야 합니다.`,
  NOT_VALID_DUPLICATE_NUMBERS: `${ERROR_MESSAGE_HEADER} 중복되지 않는 6개의 번호여야 합니다.`,
  NOT_VALID_LOTTO_NUMBER_RANGE: `${ERROR_MESSAGE_HEADER} 로또 번호는 1부터 45 사이의 숫자여야 합니다.`,
  NOT_VALID_DUPLICATE_WINNING_NUMBERS: `${ERROR_MESSAGE_HEADER} 당첨 번호와 중복된 숫자가 없어야 합니다.`,
  NOT_VALID_LOTTO_NUMBER_COUNT: `${ERROR_MESSAGE_HEADER} 로또 번호는 6개여야 합니다.`,
};

export default ERROR_MESSAGE;
