const GET_LOTTO_PURCHASE_AMOUNT_MESSAGE = '구입금액을 입력해 주세요.\n';

const GET_LOTTO_COMMON_WINNING_NUMBERS_MESSAGE = '당첨 번호를 입력해 주세요.\n';

const GET_LOTTO_BONUS_WINNING_NUMBERS_MESSAGE = '보너스 번호를 입력해 주세요.\n';

export default {
  GET_LOTTO_PURCHASE_AMOUNT_MESSAGE,
  GET_LOTTO_COMMON_WINNING_NUMBERS_MESSAGE,
  GET_LOTTO_BONUS_WINNING_NUMBERS_MESSAGE,
};
