export const LOTTO_CONSTANT = Object.freeze({
  MONEY_UNIT: 1000,
  MIN_LOTTO_RANGE: 1,
  MAX_LOTTO_RANGE: 45,
  LOTTO_LENGTH: 6,
  MIN_MATCH_COUNT: 3,
  MAX_MATCH_COUNT: 6,
  MATCH_COUNT_FIVE: 5,
  FOR_PERCENTAGE_NUMBER: 100,
});
