const LOTTO_TICKET_PRICE = 1000;
const LOTTO_MIN_NUMBER = 1;
const LOTTO_MAX_NUMBER = 45;
const REMAINING_BALANCE = 0;
const AMOUNT_MIN_NUMBER = 0;
const AMOUNT_MAX_NUMBER = 200000;
const COMMON_WINNING_NUMBERS_SIZE = 6;
const BONUS_WINNING_NUMBERS_SIZE = 1;

export default {
  LOTTO_TICKET_PRICE,
  LOTTO_MIN_NUMBER,
  LOTTO_MAX_NUMBER,
  AMOUNT_MIN_NUMBER,
  AMOUNT_MAX_NUMBER,
  REMAINING_BALANCE,
  COMMON_WINNING_NUMBERS_SIZE,
  BONUS_WINNING_NUMBERS_SIZE,
}