const LOTTO_TICKET_PRICE = 1000;
const LOTTO_MIN_NUMBER = 1;
const LOTTO_MAX_NUMBER = 45;
const REMAINING_BALANCE = 0;
const AMOUNT_MIN_NUMBER = 0;
const AMOUNT_MAX_NUMBER = 200000;
const RANK_RANGE = 6;
const LOTTO_SELLECT_NUMBER_COUNT = 6;
const COMMON_WINNING_NUMBERS_SIZE = 6;
const BONUS_WINNING_NUMBERS_SIZE = 1;
const DELIMITER = ',';
const HYPON = '-';
const QUANTITY = '개';
const LOTTO_SELLECT_NUMBER_CARD = 'LottoSellectNumberCard';
const STATISTICS_SUFFIX = '%입니다.';
const STATISTICS_PREFIX = '총 수익률은 ';
const WINNING_STATISTICS = '당첨통계';

const THREE_MATCH = '3개 일치';
const FOUR_MATCH = '4개 일치';
const FIVE_MATCH = '5개 일치';
const FIVE_AND_BONUS_MATCH = '5개 일치, 보너스 볼 일치';
const SIX_MATCH = '6개 일치';
const OPTION_NONE = '해당없음';

const THREE_MATCH_AMOUNT_STRING = '(5,000원)';
const FOUR_MATCH_AMOUNT_STRING = '(50,000원)';
const FIVE_MATCH_AMOUNT_STRING = '(1,500,000원)';
const FIVE_AND_BONUS_MATCH_AMOUNT_STRING = '(30,000,000원)';
const SIX_MATCH_AMOUNT_STRING = '(2,000,000,000원)';

const THREE_MATCH_AMOUNT = 5000;
const FOUR_MATCH_AMOUNT = 50000;
const FIVE_MATCH_AMOUNT = 1500000;
const FIVE_AND_BONUS_MATCH_AMOUNT = 30000000;
const SIX_MATCH_AMOUNT = 2000000000;

const WINNUNG_CONDITIONS = {
  '6개 일치': [6, 0],
  '5개 일치, 보너스 볼 일치': [5, 1],
  '5개 일치': [5, 0],
  '4개 일치': [4, 0],
  '3개 일치': [3, 0],
};

const THREE_MATCHS = {
  name: THREE_MATCH,
  amountString: THREE_MATCH_AMOUNT_STRING,
  amount: THREE_MATCH_AMOUNT,
};

const FOUR_MATCHS = {
  name: FOUR_MATCH,
  amountString: FOUR_MATCH_AMOUNT_STRING,
  amount: FOUR_MATCH_AMOUNT,
};

const FIVE_MATCHS = {
  name: FIVE_MATCH,
  amountString: FIVE_MATCH_AMOUNT_STRING,
  amount: FIVE_MATCH_AMOUNT,
};

const FIVE_AND_BONUS_MATCHS = {
  name: FIVE_AND_BONUS_MATCH,
  amountString: FIVE_AND_BONUS_MATCH_AMOUNT_STRING,
  amount: FIVE_AND_BONUS_MATCH_AMOUNT,
};

const SIX_MATCHS = {
  name: SIX_MATCH,
  amountString: SIX_MATCH_AMOUNT_STRING,
  amount: SIX_MATCH_AMOUNT,
};

export default {
  LOTTO_TICKET_PRICE,
  LOTTO_MIN_NUMBER,
  LOTTO_MAX_NUMBER,
  AMOUNT_MIN_NUMBER,
  AMOUNT_MAX_NUMBER,
  REMAINING_BALANCE,
  LOTTO_SELLECT_NUMBER_COUNT,
  COMMON_WINNING_NUMBERS_SIZE,
  BONUS_WINNING_NUMBERS_SIZE,
  DELIMITER,
  LOTTO_SELLECT_NUMBER_CARD,
  WINNUNG_CONDITIONS,
  RANK_RANGE,
  WINNING_STATISTICS,
  THREE_MATCH,
  FOUR_MATCH,
  FIVE_MATCH,
  FIVE_AND_BONUS_MATCH,
  SIX_MATCH,
  OPTION_NONE,
  HYPON,
  QUANTITY,
  THREE_MATCHS,
  FOUR_MATCHS,
  FIVE_MATCHS,
  FIVE_AND_BONUS_MATCHS,
  SIX_MATCHS,
  STATISTICS_SUFFIX,
  STATISTICS_PREFIX,
};
