const STATIC_NUMBER = Object.freeze({
  PURCHASE_AMOUNT_SPLIT: 1_000,
  LOTTO_START_NUMBER: 1,
  LOTTO_END_NUMBER: 45,
  LOTTO_COUNT: 6,
  FIRST_PLACE: 1,
  SECOND_PLACE: 2,
  THIRD_PLACE: 3,
  FOURTH_PLACE: 4,
  FIFTH_PLACE: 5,
  PERCENT: 100,
});

export default STATIC_NUMBER;
