const GAME_PRIZES = Object.freeze({
  FIRST_PRIZE: '1등',
  SECOND_PRIZE: '2등',
  THIRD_PRIZE: '3등',
  FOURTH_PRIZE: '4등',
  FIFTH_PRIZE: '5등',
});

const NUMBER = Object.freeze({
  ONE_HUNDRED: 100,
  FORTY_FIVE: 45,
  SIX: 6,
  FIVE: 5,
  FOUR: 4,
  THREE: 3,
  ONE: 1,
  ZERO: 0,
});

const PRIZE_AMOUNTS = Object.freeze({
  FIRST_PRIZE_AMOUNT: 2000000000,
  SECOND_PRIZE_AMOUNT: 30000000,
  THIRD_PRIZE_AMOUNT: 1500000,
  FOURTH_PRIZE_AMOUNT: 50000,
  FIFTH_PRIZE_AMOUNT: 5000,
  TICKET_PRICE_AMOUNT: 1000,
});

export { GAME_PRIZES, NUMBER, PRIZE_AMOUNTS };
